nextest-version = "0.9.98"
experimental = ["setup-scripts"]

[profile.default]
final-status-level = "slow"

[profile.ci]
# Don't fail fast in CI to run the full test suite.
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 1 }

[[profile.ci.overrides]]
# These tests are a bit flaky on Mac GHA CI runners due to resource exhaustion.
platform = 'cfg(target_os = "macos")'
filter = '(package(nextest-runner) and binary(integration)) or package(integration-tests)'
retries = { count = 3, backoff = "fixed", delay = "1s" }
