name: Build & Release on Tag
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Build release
        run: cargo build --release
      - name: Upload release binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: invoke-llm
          path: target/release/invoke-llm
      - name: Create GitHub Release & Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/invoke-llm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
