name: unit tests
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.rs'
  pull_request:
    paths:
      - '**/*.rs'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/lockfiles') }}-${{ secrets.CACHE_VERSION || 'v1' }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ hashFiles('**/lockfiles') }}-${{ secrets.CACHE_VERSION || 'v1' }}-
      - name: Update and Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libavfilter-dev \
            libavdevice-dev \
            libavutil-dev
      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
        with:
          key: stable
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo nextest run --config-file .cargo/nextest.toml --profile ci
      # - name: Install cargo-careful
      #   run: cargo install cargo-careful
      # - name: Run cargo-careful
      #   run: cargo +nightly careful test --target x86_64-unknown-linux-gnu
